nguage: node_jsi
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  ######
  - echo "Begin to build reverseproxy image"
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy nlcd/reverseproxy:v1
  - echo "Finish to build reverseproxy image"
  ######
  - echo "Begin to build udagram-api-user image"
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user nlcd/udagram-api-user:v1
  - echo "Finish to build udagram-api-user image"
  #####
  - echo "Begin to build udagram-api-feed image"
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed nlcd/udagram-api-feed:v1
  - echo "Finish to build udagram-api-feed image"
  #####
  - echo "Begin to build udagram-frontend image"
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend nlcd/udagram-frontend:v1
  - echo "Finish to build udagram-frontend image"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nlcd/reverseproxy:v1
  - docker push nlcd/udagram-api-user:v1
  - docker push nlcd/udagram-api-feed:v1
  - docker push nlcd/udagram-frontend:v1
